### ISSUE TITLE
V3 UI Tweaks

### ISSUE THREAD

**Issue by nwmac** [SUSE/stratos#278]
Helm release
- Hide overview tab from Helm release summary
- Make namespace a link
- Tidy up status display (lowercase)
- Don't duplicate pods and containers tiles
- Pods List - node link does not go to node detail
Workloads
- Namespace can be a link
- Capitalize first letter of status

Pods
 - Namespace should be a link in the list

**Comment by richard-cox** [comment]
General
- [x] RC Console Setup - Header should be suse green
- [x] RC Remove Helm feature from tech preview
- [x] RC Fix Kube Connect dialog
- [x] RC Register Stepper - Confirm Kube `skip ssl` option is working correctly - #292
- [x] Improve cert error feedback when connecting kube endpoint - #292
- [x] RC Add `Age` column to all kube tables

Kube - Nodes
- [x] RC `No. of Pods` --> `Pods`

Kube - Namespaces
- [x] RC `No. of Pods` --> `Pods`

Kube - Pods
- [x] RC Pod status used to have colour coded border. Needs to come back

Kube - Node - Summary
- [x] RC Out of disk shows as `unknown`. Should have a map of accepted values and show those. Should also use this in the Kube summary charts

Workloads
- [x] RC Create card view, make default
- [ ] Use new side nav icon
- [x] RC Make `namespace` a link
- [x] RC capitalise `status` value

Workload - Summary
- [x] RC Show loading indicator for charts/resources (both come from same place)
- [x] RC Title charts as `Pods and Containers` and resources as `All Resources`
- [x] RC Make `namespace` a link
- [x] RC capitalise `status` value
- [x] RC hide overview tab
- [x] RC Pods Chart - Use same colours as container chart, consistently show 'not runnin'

All Pods Lists
- [x] RC Hide namespaces everywhere except at top level
- [x] RC Click on pod name to open side panel which shows same content as overview chart click

All Service Lists
- [x] RC Click on service name to open side panel which shows same content as overview chart click

Favourites
- [x] RC Helm Endpoint shows up as 'disconnected'

Confirmation Modal
- [x] RC If the 'match text' flag is set assume the critical flag is also set. this should then show icon and warning button

Nav Bar
- [x] RC Swap kube and workloads position

Sidebar Preview
- [x] RC Title should not be green
 
Create Issues For
- [x] Register Stepper - Only register at end of flow - https://github.com/cloudfoundry/stratos/issues/4107
- [x] Kube - Pod --> Container View - #288
  - Create a level underneath pod level for pod containers
  - Allow user to view container logs
  - Allow user to exec in to container
- [x] Bug - Monocular - Chart Summary - Relative links in readme are broken. Could clean these at the same time as other link tweak - #289
- [x] Align Pod Info with kubectl get pods - #290
